
server:
  hostname: "test-server"
  ip_address: "192.168.1.10"
  os: "Ubuntu 20.04"
  user_groups: ["admin", "dev"]
  firewall_rules:
    - "ALLOW IN 22/tcp"
    - "ALLOW IN 80/tcp"
    - "DENY IN all"
